*&---------------------------------------------------------------------*
*& Include          ZJOG_VELHA_OO_V2_TOP
*&---------------------------------------------------------------------*
TABLES: sscrfields.
*CLASS lcl_jogo DEFINITION DEFERRED.
DATA: lo_jogo TYPE REF TO lcl_jogo.
SELECTION-SCREEN BEGIN OF BLOCK b1 WITH FRAME TITLE TEXT-200.
SELECTION-SCREEN PUSHBUTTON /1(3) p_but1 USER-COMMAND but1.
SELECTION-SCREEN PUSHBUTTON 5(3)  p_bub1 USER-COMMAND bub1.
SELECTION-SCREEN PUSHBUTTON 9(3)  p_buc1 USER-COMMAND buc1.
SELECTION-SCREEN PUSHBUTTON /1(3) p_but2 USER-COMMAND but2.
SELECTION-SCREEN PUSHBUTTON 5(3)  p_bub2 USER-COMMAND bub2.
SELECTION-SCREEN PUSHBUTTON 9(3)  p_buc2 USER-COMMAND buc2.
SELECTION-SCREEN PUSHBUTTON /1(3) p_but3 USER-COMMAND but3.
SELECTION-SCREEN PUSHBUTTON 5(3)  p_bub3 USER-COMMAND bub3.
SELECTION-SCREEN PUSHBUTTON 9(3)  p_buc3 USER-COMMAND buc3.
SELECTION-SCREEN COMMENT /1(11)   p_comm.
SELECTION-SCREEN END OF BLOCK b1.

SELECTION-SCREEN BEGIN OF BLOCK b2 WITH FRAME TITLE TEXT-100.
SELECTION-SCREEN PUSHBUTTON /3(6) p_inicio USER-COMMAND inicio.
SELECTION-SCREEN END OF BLOCK b2.